# Generated by Django 6.1.1 on 2026-09-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringrecord',
            name='remarks',
            field=models.CharField(choices=[('Present / Class Ongoing', 'Present / Class Ongoing'), ('Present but Late', 'Present but Late'), ('Faculty Not Present', 'Faculty Not Present'), ('Room/Class Transferred', 'Room/Class Transferred'), ('Official Activity/Approved Absence', 'Official Activity/Approved Absence'), ('No Students Present', 'No Students Present'), ('Other', 'Other')], default='Present / Class Ongoing', max_length=100),
        ),
    ]
