# Generated by Django 6.1.1 on 2026-09-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_reporttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
