# Generated by Django 6.1.1 on 2026-09-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_subject_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringrecord',
            name='transfer_room',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
