# Generated by Django 6.1.1 on 2026-09-22 07:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_monitoringrecord_transfer_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringrecord',
            name='record_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
