# Generated by Django 6.1.1 on 2026-09-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alter_monitoringrecord_record_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringrecord',
            name='status',
            field=models.CharField(choices=[('MONITORED', 'Monitored'), ('LATE', 'Late'), ('MISSED', 'Missed')], default='MONITORED', max_length=20),
        ),
    ]
