# Generated by Django 6.1.1 on 2026-09-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_monitoringrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringrecord',
            name='missed_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='monitoringrecord',
            name='other_remarks',
            field=models.TextField(blank=True),
        ),
    ]
