# Generated by Django 6.1.1 on 2026-09-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_monitoringrecord_missed_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringrecord',
            name='remarks',
            field=models.TextField(blank=True, default='Present / Class Ongoing'),
        ),
    ]
