# Generated by Django 6.1.1 on 2026-09-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_systemadministrator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringrecord',
            name='status',
        ),
        migrations.AlterField(
            model_name='monitoringrecord',
            name='remarks',
            field=models.TextField(blank=True, default='Monitored'),
        ),
    ]
