# Generated by Django 6.1.1 on 2026-09-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_remove_monitoringrecord_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='classification',
            field=models.CharField(choices=[('PART_TIME', 'Part-Time'), ('REGULAR', 'Regular')], default='PART_TIME', max_length=20),
        ),
    ]
